defmodule PhoenixKit.Modules.Emails.Web.Blocklist do
  @moduledoc """
  LiveView for managing email blocklist and blocked addresses.

  Provides comprehensive management of blocked email addresses, including:

  - **Blocklist Viewing**: List all blocked email addresses with filtering
  - **Block Management**: Add/remove email addresses from blocklist
  - **Bulk Operations**: Import/export blocklists, bulk add/remove
  - **Temporary Blocks**: Set expiration dates for temporary blocks
  - **Block Reasons**: Categorize blocks by reason (spam, bounce, manual, etc.)
  - **Search & Filter**: Find blocked addresses by email, reason, or date

  ## Features

  - **Real-time Updates**: Live updates when blocks are added/removed
  - **CSV Import/Export**: Bulk management through CSV files
  - **Automatic Blocking**: Integration with rate limiter for auto-blocks
  - **Audit Trail**: Track who blocked addresses and when
  - **Expiration Management**: Automatic cleanup of expired blocks
  - **Statistics**: Analytics on blocked addresses and reasons

  ## Route

  This LiveView is mounted at `{prefix}/admin/emails/blocklist` and requires
  appropriate admin permissions.

  Note: `{prefix}` is your configured PhoenixKit URL prefix (default: `/phoenix_kit`).

  The route is auto-generated by PhoenixKit from `admin_tabs/0` at compile time and
  injected into `live_session :phoenix_kit_admin`. Do not declare this route in your
  parent app's `router.ex`. See `phoenix_kit/guides/custom-admin-pages.md`.

  ## Permissions

  Access is restricted to users with admin or owner roles in PhoenixKit.
  """

  use PhoenixKitWeb, :live_view

  # Whitelist of fields that may be passed to RateLimiter.list_blocklist/1
  # :order_by. Anything outside this set falls back to the default inserted_at.
  # Declared before the UrlState spec below so both the URL decoder and
  # validate_sort_by/1 read the same list — a sort column added to one but not
  # the other is accepted by the header click and then silently dropped by the
  # URL, which is exactly how the reason filter broke.
  @sort_fields [:email, :reason, :inserted_at, :expires_at]

  # search_term, reason_filter, status_filter, sort_by, sort_dir, and page all
  # live in the URL so the list is a real, shareable, reload-proof address.
  use PhoenixKitWeb.Live.UrlState,
    params: [
      search_term: [default: "", url_key: "q"],
      # No `in:` here on purpose. Reasons are free-form strings: the schema
      # casts :reason without validate_inclusion, the SQS processor writes
      # "hard_bounce", the rate limiter writes "complaint_spam", and CSV import
      # takes whatever the file says. The dropdown is built from the reasons
      # actually present in the data, so a fixed whitelist would silently
      # reject the very options the screen offers — and since the rejected
      # value falls back to the default, the resulting URL is unchanged and
      # the callback never fires, leaving the click with no visible effect.
      reason_filter: [default: "", url_key: "reason"],
      status_filter: [default: "all", url_key: "status", in: ~w(all expired)],
      sort_by: [default: :inserted_at, url_key: "sort", cast: :atom, in: @sort_fields],
      sort_dir: [default: :desc, url_key: "dir", cast: :atom, in: [:asc, :desc]],
      page: [default: 1, url_key: "page", cast: :integer, min: 1]
    ]

  use Gettext, backend: PhoenixKit.Modules.Emails.Gettext
  import PhoenixKitWeb.Components.Core.Icon
  import PhoenixKitWeb.Components.Core.TableDefault

  require Logger

  alias PhoenixKit.Modules.Emails
  alias PhoenixKit.Modules.Emails.RateLimiter
  alias PhoenixKit.Modules.Emails.Utils
  alias PhoenixKit.Utils.Date, as: UtilsDate
  alias PhoenixKit.Utils.Routes

  # Auto-refresh every 30 seconds
  @refresh_interval 30_000

  # Items per page for pagination
  @per_page 50

  ## --- Lifecycle Callbacks ---

  @impl true
  def mount(_params, _session, socket) do
    # Check if email system is enabled
    if Emails.enabled?() do
      # Get project title from settings

      # Schedule periodic refresh
      if connected?(socket) do
        Process.send_after(self(), :refresh_blocklist, @refresh_interval)
      end

      # :search_term, :reason_filter, :status_filter, :sort_by, :sort_dir, and
      # :page are set from the query string by UrlState before mount/3 runs.
      # Re-assigning them here would overwrite a shared link's state with the
      # defaults. The list is loaded by handle_url_state/2 instead.
      socket =
        socket
        |> assign(:loading, true)
        |> assign(:blocked_emails, [])
        |> assign(:total_blocked, 0)
        |> assign(:per_page, @per_page)
        |> assign(:selected_emails, [])
        |> assign(:show_add_form, false)
        |> assign(:show_import_form, false)
        |> assign(:bulk_action, nil)
        |> assign(:last_updated, UtilsDate.utc_now())
        |> assign(:statistics, %{})
        |> assign(:page_title, gettext("Email Blocklist"))
        |> assign(:page_subtitle, gettext("Manage blocked email addresses"))

      {:ok, socket}
    else
      {:ok,
       socket
       |> put_flash(:error, gettext("Email is not enabled"))
       |> push_navigate(to: Routes.path("/admin"))}
    end
  end

  # The list is loaded here rather than in mount/3: UrlState calls this after
  # mount and on every change to the query string, so one code path handles the
  # first render, a shared link, and the Back button alike.
  @impl true
  def handle_url_state(_state, socket), do: load_blocklist_data(socket)

  # Required because this module annotates other callbacks with @impl true.
  # The UrlState __before_compile__ would inject a bare stub, but a bare def
  # in an @impl-annotated module triggers a missing-@impl warning that
  # --warnings-as-errors promotes to a compile error.
  @impl true
  def handle_params(_params, _uri, socket), do: {:noreply, socket}

  ## --- Event Handlers ---

  @impl true
  def handle_event("refresh", _params, socket) do
    {:noreply,
     socket
     |> assign(:loading, true)
     |> load_blocklist_data()}
  end

  # replace: true — the input is debounced, so each pause in typing would
  # otherwise write a history entry and Back would walk the query backwards
  # instead of leaving the page. The clear-search button also fires this event
  # with search="" and inherits the same replace: true behaviour.
  @impl true
  def handle_event("filter_search", %{"search" => search_term}, socket) do
    {:noreply, push_url_state(socket, [search_term: search_term], replace: true)}
  end

  @impl true
  def handle_event("filter_reason", %{"reason" => reason}, socket) do
    {:noreply, push_url_state(socket, reason_filter: reason)}
  end

  @impl true
  def handle_event("filter_status", %{"status" => status}, socket) do
    {:noreply, push_url_state(socket, status_filter: status)}
  end

  @impl true
  def handle_event("toggle_sort", %{"by" => by}, socket) do
    # Clicking a sortable column header: validate the field, then toggle the
    # direction if it's already the active sort, otherwise switch to that field
    # ascending. Page resets to 1 automatically (UrlState page_param).
    field = validate_sort_by(by)

    sort_dir =
      if field == socket.assigns.sort_by do
        if socket.assigns.sort_dir == :asc, do: :desc, else: :asc
      else
        :asc
      end

    {:noreply, push_url_state(socket, sort_by: field, sort_dir: sort_dir)}
  end

  @impl true
  def handle_event("change_page", %{"page" => page}, socket) do
    case Integer.parse(page) do
      {page_num, _} when page_num > 0 ->
        {:noreply, push_url_state(socket, page: page_num)}

      _ ->
        {:noreply, socket}
    end
  end

  @impl true
  def handle_event("toggle_add_form", _params, socket) do
    {:noreply,
     socket
     |> assign(:show_add_form, !socket.assigns.show_add_form)}
  end

  @impl true
  def handle_event("toggle_import_form", _params, socket) do
    {:noreply,
     socket
     |> assign(:show_import_form, !socket.assigns.show_import_form)}
  end

  @impl true
  def handle_event("add_block", params, socket) do
    %{
      "email" => email,
      "reason" => reason,
      "expires_at" => expires_at
    } = params

    opts = []

    opts =
      if expires_at && expires_at != "" do
        case Date.from_iso8601(expires_at) do
          {:ok, date} ->
            expires_datetime = DateTime.new!(date, ~T[23:59:59])
            [expires_at: expires_datetime] ++ opts

          _ ->
            opts
        end
      else
        opts
      end

    case RateLimiter.add_to_blocklist(email, reason, opts) do
      :ok ->
        {:noreply,
         socket
         |> assign(:show_add_form, false)
         |> put_flash(:info, gettext("Email address blocked successfully"))
         |> load_blocklist_data()}

      {:error, reason} ->
        {:noreply,
         socket
         |> put_flash(:error, gettext("Failed to block email: %{reason}", reason: reason))}
    end
  end

  @impl true
  def handle_event("remove_block", %{"email" => email}, socket) do
    RateLimiter.remove_from_blocklist(email)

    {:noreply,
     socket
     |> put_flash(:info, gettext("Email address unblocked successfully"))
     |> load_blocklist_data()}
  end

  @impl true
  def handle_event("toggle_email_selection", %{"email" => email}, socket) do
    selected = socket.assigns.selected_emails

    new_selected =
      if email in selected do
        List.delete(selected, email)
      else
        [email | selected]
      end

    {:noreply,
     socket
     |> assign(:selected_emails, new_selected)}
  end

  @impl true
  def handle_event("select_all_visible", _params, socket) do
    all_emails = Enum.map(socket.assigns.blocked_emails, & &1.email)

    {:noreply,
     socket
     |> assign(:selected_emails, all_emails)}
  end

  @impl true
  def handle_event("clear_selection", _params, socket) do
    {:noreply,
     socket
     |> assign(:selected_emails, [])
     |> assign(:bulk_action, nil)}
  end

  @impl true
  def handle_event("set_bulk_action", %{"action" => action}, socket) do
    {:noreply,
     socket
     |> assign(:bulk_action, action)}
  end

  @impl true
  def handle_event("execute_bulk_action", _params, socket) do
    case socket.assigns.bulk_action do
      "remove" ->
        execute_bulk_remove(socket)

      "export" ->
        execute_bulk_export(socket)

      _ ->
        {:noreply,
         socket
         |> put_flash(:error, gettext("Invalid bulk action"))}
    end
  end

  @impl true
  def handle_event("export_blocklist", %{"format" => format}, socket) do
    case format do
      "csv" ->
        csv_content = export_blocklist_csv(socket.assigns.blocked_emails)
        filename = "email_blocklist_#{Date.utc_today()}.csv"

        {:noreply,
         socket
         |> push_event("download", %{
           filename: filename,
           content: csv_content,
           mime_type: "text/csv"
         })}

      "json" ->
        json_content = Utils.Json.encode_pretty!(socket.assigns.blocked_emails)
        filename = "email_blocklist_#{Date.utc_today()}.json"

        {:noreply,
         socket
         |> push_event("download", %{
           filename: filename,
           content: json_content,
           mime_type: "application/json"
         })}

      _ ->
        {:noreply,
         socket
         |> put_flash(:error, gettext("Unsupported export format"))}
    end
  end

  @impl true
  def handle_event("import_csv", %{"csv_content" => csv_content}, socket) do
    case import_blocklist_csv(csv_content) do
      {:ok, imported_count} ->
        {:noreply,
         socket
         |> assign(:show_import_form, false)
         |> put_flash(
           :info,
           gettext("Successfully imported %{count} blocked emails", count: imported_count)
         )
         |> load_blocklist_data()}

      {:error, reason} ->
        {:noreply,
         socket
         |> put_flash(:error, gettext("Import failed: %{reason}", reason: reason))}
    end
  end

  @impl true
  def handle_info(:refresh_blocklist, socket) do
    # Schedule next refresh
    Process.send_after(self(), :refresh_blocklist, @refresh_interval)

    {:noreply,
     socket
     |> assign(:last_updated, UtilsDate.utc_now())
     |> load_blocklist_data()}
  end

  defp load_blocklist_data(socket) do
    total_blocked = count_blocked_emails(build_filters(socket.assigns))

    # Calculate total pages for pagination. Floor of 1 so an empty list still
    # has a page to sit on, which is what clamp_page/2 below measures against.
    total_pages = max(ceil(total_blocked / socket.assigns.per_page), 1)

    # Now that :page comes out of the URL it can point past the end of the list
    # — ?page=900 on a two-page list, or the 1_000_000 ceiling UrlState allows.
    # Clamping before the query keeps the offset meaningful and, more to the
    # point, keeps the template's max(1, @page - 2)..min(@total_pages, @page + 2)
    # window ascending: left unclamped it becomes a *descending* range and
    # renders one button per skipped page. Assigning the corrected page directly
    # is safe — UrlState reads its merge base back from the assigns, so the next
    # patch carries this value rather than resurrecting the one from the URL.
    socket = assign(socket, :page, clamp_page(socket.assigns.page, total_pages))

    # Load blocked emails using RateLimiter API
    blocked_emails = load_blocked_emails(build_filters(socket.assigns))
    statistics = load_blocklist_statistics()

    socket
    |> assign(:blocked_emails, blocked_emails)
    |> assign(:total_blocked, total_blocked)
    |> assign(:total_pages, total_pages)
    |> assign(:statistics, statistics)
    |> assign(:loading, false)
  end

  defp build_filters(assigns) do
    opts = %{}

    opts =
      if assigns.search_term && assigns.search_term != "" do
        Map.put(opts, :search, assigns.search_term)
      else
        opts
      end

    opts =
      if assigns.reason_filter && assigns.reason_filter != "" do
        Map.put(opts, :reason, assigns.reason_filter)
      else
        opts
      end

    opts =
      if assigns.status_filter == "expired" do
        Map.put(opts, :include_expired, true)
      else
        opts
      end

    # Pagination
    offset = (assigns.page - 1) * assigns.per_page

    opts
    |> Map.put(:limit, assigns.per_page)
    |> Map.put(:offset, offset)
    |> Map.put(:order_by, assigns.sort_by)
    |> Map.put(:order_dir, assigns.sort_dir)
  end

  # The page a request can actually land on. `@doc false` rather than private so
  # the pagination-window regression can be pinned by a test without a database.
  @doc false
  @spec clamp_page(integer(), integer()) :: integer()
  def clamp_page(page, total_pages) when is_integer(page) and is_integer(total_pages) do
    page |> max(1) |> min(max(total_pages, 1))
  end

  defp validate_sort_by(value) when is_atom(value) do
    if value in @sort_fields, do: value, else: :inserted_at
  end

  defp validate_sort_by(value) when is_binary(value) do
    case Enum.find(@sort_fields, fn field -> Atom.to_string(field) == value end) do
      nil -> :inserted_at
      field -> field
    end
  end

  defp validate_sort_by(_), do: :inserted_at

  defp load_blocked_emails(filters) do
    RateLimiter.list_blocklist(filters)
  end

  defp count_blocked_emails(filters) do
    # Remove pagination params for count
    filters
    |> Map.delete(:limit)
    |> Map.delete(:offset)
    |> RateLimiter.count_blocklist()
  end

  defp load_blocklist_statistics do
    RateLimiter.get_blocklist_stats()
  end

  defp execute_bulk_remove(socket) do
    selected_emails = socket.assigns.selected_emails

    success_count =
      Enum.reduce(selected_emails, 0, fn email, acc ->
        RateLimiter.remove_from_blocklist(email)
        acc + 1
      end)

    message =
      gettext("Removed %{success} of %{total} emails from blocklist",
        success: success_count,
        total: length(selected_emails)
      )

    {:noreply,
     socket
     |> assign(:selected_emails, [])
     |> assign(:bulk_action, nil)
     |> put_flash(:info, message)
     |> load_blocklist_data()}
  end

  defp execute_bulk_export(socket) do
    selected_emails = socket.assigns.selected_emails
    blocked_data = Enum.filter(socket.assigns.blocked_emails, &(&1.email in selected_emails))

    csv_content = export_blocklist_csv(blocked_data)
    filename = "selected_blocklist_#{Date.utc_today()}.csv"

    {:noreply,
     socket
     |> push_event("download", %{
       filename: filename,
       content: csv_content,
       mime_type: "text/csv"
     })}
  end

  defp export_blocklist_csv(blocked_emails) do
    headers = "email,reason,added_at,expires_at\n"

    rows =
      Enum.map_join(blocked_emails, "\n", fn blocked ->
        expires_str =
          if blocked.expires_at,
            do: Date.to_iso8601(DateTime.to_date(blocked.expires_at)),
            else: ""

        added_str = Date.to_iso8601(DateTime.to_date(blocked.inserted_at))

        [blocked.email, blocked.reason, added_str, expires_str]
        |> Enum.map_join(",", &escape_csv_field/1)
      end)

    headers <> rows
  end

  # Escape CSV field value, including formula injection protection.
  # Cells starting with =, +, -, @, tab, or CR are prefixed with a single quote
  # to prevent formula execution when opened in spreadsheet applications.
  defp escape_csv_field(nil), do: ""

  defp escape_csv_field(value) when is_binary(value) do
    value = sanitize_csv_formula(value)

    if String.contains?(value, [",", "\"", "\n", "\r"]) do
      "\"#{String.replace(value, "\"", "\"\"")}\""
    else
      value
    end
  end

  defp escape_csv_field(value), do: value |> to_string() |> escape_csv_field()

  defp sanitize_csv_formula(<<first, _::binary>> = value)
       when first in [?=, ?+, ?-, ?@, ?\t, ?\r] do
    "'" <> value
  end

  defp sanitize_csv_formula(value), do: value

  defp import_blocklist_csv(csv_content) do
    lines =
      String.split(csv_content, "\n") |> Enum.map(&String.trim/1) |> Enum.reject(&(&1 == ""))

    # Skip header line if it looks like headers
    lines =
      case List.first(lines) do
        "email,reason" <> _ -> List.delete_at(lines, 0)
        _ -> lines
      end

    imported_count =
      Enum.reduce(lines, 0, fn line, acc ->
        case parse_csv_line(line) do
          {:ok, email, reason, expires_at} ->
            opts = if expires_at, do: [expires_at: expires_at], else: []

            case RateLimiter.add_to_blocklist(email, reason, opts) do
              :ok -> acc + 1
              _ -> acc
            end

          _ ->
            acc
        end
      end)

    {:ok, imported_count}
  rescue
    _ -> {:error, "Invalid CSV format"}
  end

  defp parse_csv_line(line) do
    parts = String.split(line, ",") |> Enum.map(&String.trim/1)

    case parts do
      [email, reason] ->
        {:ok, email, reason, nil}

      [email, reason, ""] ->
        {:ok, email, reason, nil}

      [email, reason, expires_str] ->
        case Date.from_iso8601(expires_str) do
          {:ok, date} -> {:ok, email, reason, DateTime.new!(date, ~T[23:59:59])}
          _ -> {:ok, email, reason, nil}
        end

      _ ->
        {:error, "Invalid line format"}
    end
  end
end
